import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Car(props) {
  const { nodes, materials } = useGLTF('/m3 finalGLAVNO.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HOOD.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HOOD_VENT.geometry}
        material={nodes.HOOD_VENT.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_HOOD_VENT.geometry}
        material={nodes.FRONT_HOOD_VENT.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FENDER.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DOOR.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_QP.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SIDE_SKIRT.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TRUNK.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LICENSE.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_BUMPER.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_BUMPER.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_GRILLES.geometry}
        material={nodes.FRONT_GRILLES.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WINDSHIELD.geometry}
        material={nodes.WINDSHIELD.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HOOD_GRILLES.geometry}
        material={nodes.HOOD_GRILLES.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RIMS.geometry}
        material={nodes.RIMS.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_RIMS.geometry}
        material={nodes.BACK_RIMS.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RIMS_BOLT.geometry}
        material={nodes.RIMS_BOLT.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_RIM_BOLT.geometry}
        material={nodes.BACK_RIM_BOLT.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_TIRES.geometry}
        material={nodes.FRONT_TIRES.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_TIRES.geometry}
        material={nodes.BACK_TIRES.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BREAK_DISK.geometry}
        material={nodes.BREAK_DISK.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BREAKS.geometry}
        material={nodes.BREAKS.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BREAK_DISK001.geometry}
        material={nodes.BREAK_DISK001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SIDE_VENT.geometry}
        material={nodes.SIDE_VENT.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SIDE_VENT_SQUARE.geometry}
        material={nodes.SIDE_VENT_SQUARE.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPOILER.geometry}
        material={nodes.SPOILER.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EXAUST.geometry}
        material={nodes.EXAUST.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SIDE_STRIPE.geometry}
        material={nodes.SIDE_STRIPE.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DOOR_HANDLE.geometry}
        material={nodes.DOOR_HANDLE.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BADGE.geometry}
        material={nodes.BADGE.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_BADGE.geometry}
        material={nodes.REAR_BADGE.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_BUMPER001.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_BUMPER002.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FENDER001.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SIDE_DETAIL.geometry}
        material={nodes.SIDE_DETAIL.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_WHEEL_ARCH.geometry}
        material={nodes.BACK_WHEEL_ARCH.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WINDOW_FRAME.geometry}
        material={nodes.WINDOW_FRAME.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WINDSHIELD_FRAME.geometry}
        material={nodes.WINDSHIELD_FRAME.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_WINDOW.geometry}
        material={nodes.BACK_WINDOW.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_WINDOW_BOLTS.geometry}
        material={nodes.BACK_WINDOW_BOLTS.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_WHEEL_ARCH.geometry}
        material={nodes.FRONT_WHEEL_ARCH.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_WINDOW.geometry}
        material={nodes.FRONT_WINDOW.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RW_FRAME.geometry}
        material={nodes.RW_FRAME.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_WINDSHIELD.geometry}
        material={nodes.REAR_WINDSHIELD.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BREAKS001.geometry}
        material={nodes.BREAKS001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_BUMPER003.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_BUMPER004.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={nodes.Circle003.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SVETLA.geometry}
        material={nodes.SVETLA.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SVETLA_2.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SVETLA_2001.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_BUMPER006.geometry}
        material={materials['Material.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_LIGHT.geometry}
        material={materials.Material}
        position={[-0.288, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_LIGHT001.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TRUNK001.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TRUNK002.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.REAR_LIGHTS_3.geometry}
        material={nodes.REAR_LIGHTS_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_HOOD_VENT001.geometry}
        material={nodes.FRONT_HOOD_VENT001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CIRCLE.geometry}
        material={nodes.CIRCLE.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['1'].geometry}
        material={nodes['1'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['2'].geometry}
        material={nodes['2'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['3'].geometry}
        material={nodes['3'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['4'].geometry}
        material={nodes['4'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['5'].geometry}
        material={nodes['5'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['6'].geometry}
        material={nodes['6'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['7'].geometry}
        material={nodes['7'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['9'].geometry}
        material={nodes['9'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['10'].geometry}
        material={nodes['10'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['11'].geometry}
        material={nodes['11'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['8'].geometry}
        material={nodes['8'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MIRROR.geometry}
        material={nodes.MIRROR.material}
      />
    </group>
  );
}

useGLTF.preload('/m3 finalGLAVNO.glb');
